services:
  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017 
    volumes:
      - mongo:/data/db
  backend:
    build: .
    ports:
      - 4000:4000
    depends_on:
      - db
volumes:
  mongo: