name: Deploy dev
on:
  push:
    branches:
      - feat/implement-ci
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [backend, frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up Nodejs v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            **/.next/cache
          key: ${{ runner.os }}-node-20-cache-${{ hashFiles('**/package-lock.json') }}

          restore-keys: ${{ runner.os }}-node-20-cache-

      - name: Setup env frontend
        run: echo "${{secrets.DEV_FE}}" > .env

      - name: Install dependencies
        run: npm install
      
      - name: Build project
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: apps/${{ matrix.app }}/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ github.sha }}
            ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:latest
          cache-from: type=registry,ref=user/app:buildcache
          cache-to: type=registry,ref=user/app:buildcache,mode=max
        
  # docker:
  #   runs-on: ubuntu-latest
  #   needs: ci
  #   strategy:
  #     matrix:
  #       app: [backend, frontend]
  #   steps:
  #     - name: Checkout code 
  #       uses: actions/checkout@v4
  #       with:
  #         fetch-depth: 0

  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3

  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v6
  #       with:
  #         context: .
  #         file: apps/${{ matrix.app }}/Dockerfile
  #         push: true
  #         tags: |
  #           ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:${{ github.sha }}
  #           ghcr.io/${{ github.repository_owner }}/${{ matrix.app }}:latest
  #         cache-from: type=registry,ref=user/app:buildcache
  #         cache-to: type=registry,ref=user/app:buildcache,mode=max
