name: Check Pull Request
on:
  push:
    branches:
      - feat/implement-ci
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: set up Nodejs v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-node-20-cache-${{ hashFiles('**/package-lock.json') }}

          restore-keys: ${{ runner.os }}-node-20-cache-
      - name: Install dependencies
        run: npm install
  # lint:
  #   runs-on: ubuntu-latest
  #   needs: setup
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: '20'

  #     - name: Cache node modules
  #       uses: actions/cache@v4
  #       with:
  #         path: '**/node_modules'
  #         key: ${{ runner.os }}-node-20-cache-${{ hashFiles('**/package-lock.json') }}
  #         restore-keys: ${{ runner.os }}-node-20-cache-

  #     - name: Install dependencies
  #       run: npm install

  #     - name: Lint code
  #       run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: |
            **/node_modules
            ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-node-20-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-20-cache-

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npx nx run backend:build
